[tool.poetry]
name = "oeis-seq"
version = "0.1.2"
description = "OEIS Integer sequences implemented in Python"
license = "MIT"
authors = ["Reid Hochstedler <reidhoch@gmail.com>"]
packages = [
    { include = "oeis" }
]


[tool.poetry.dependencies]
python = "^3.8"

[tool.poetry.dev-dependencies]
black = "21.5b1"
flake8 = "^3.9"
hypothesis = "^6.8"
matplotlib = "^3.4"
mypy = "^0.901"
pylint = "^2.8"
pytest = "^6.2"
pytest-cov = "^2.11"

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"
