[tool.poetry]
name = "oeis-seq"
version = "0.1.4"
description = "OEIS Integer sequences implemented in Python"
license = "MIT"
authors = ["Reid Hochstedler <reidhoch@gmail.com>"]
packages = [
    { include = "oeis" }
]


[tool.poetry.dependencies]
python = "^3.8"

[tool.poetry.dev-dependencies]
black = "21.6b0"
flake8 = "^3.9"
flake8-bugbear = "^21.4"
flake8-commas = "^2.0"
flake8-docstrings = "^1.6"
flake8-import-order = "^0.18"
flake8-pytest-style = "^1.5"
hypothesis = "^6.8"
matplotlib = "^3.4"
mypy = "^0.902"
pytest = "^6.2"
pytest-cov = "^2.11"

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"
